### ISSUE TITLE
Use DVC pipeline

### ISSUE THREAD

**Issue by ybracke** [ybracke/transnormer#6]
- [x] Set-up DVC and DVC experiments on branch `dev-setup-dvc`.
    - [x] README entry that explains the basic idea and workflow with DVC experiments.
- [x] Merge branch `dev-setup-dvc` into `dev`.
- [x] Remove dummy experiments from DVC exp history

**Comment by ybracke** [comment]
### Workflow

I will have a branch called `exp`. This branch is not used for development but only for running experiments. New changes from `dev` are merged into `exp` from time to time, but `exp` can't be merged into other branches (can you force this behavior?). 
The `exp` branch needs a different `.gitignore` file than the other branches. While all other branches should ignore all files related to dvc (`*.dvc`, `training_config.toml`|`params.yaml`, ...) `exp` should track these files. All branches should keep ignoring the actual data files (`data/*`, `models/*`) because these are tracked by dvc.

```
*   *   *   *   *   *   *   dev
 \   \   \   \   \   \   \
  *---*---*---*---*---*---* exp
```

Experiments are run on branch `exp` with `dvc exp ...`

**Comment by ybracke** [comment]
### Workflow

Preface:
* Always run experiments on a designated branch, e.g. `dev` (`git switch dev`)
* Always commit changes to that branch before running the experiment (exception: changes to the config file)

1. change parameters in config file (obsolete if you do --set-params in step 2) 
2. dvc exp run [--set-param ... ]
   -> runs experiment and creates hidden commit, tracked by dvc
3. git restore . 
   -> removes the changes that were created by running the experiment
      from the repo, so that they do not get committed to git
4. dvc exp show [-A]
   -> shows the experiments done on the current HEAD (on all commits)

**Comment by ybracke** [comment]
### Setting up dvc for my repo

#### Part 1
Switch to correct branch
Add dvc to requirements
Install dvc
Init dvc
Set-up local remote storage with dvc for data/model files
Add these files to dvc
Commit the first dvc stuff to git
Test whether it works to push/pull from local remote storage

#### Part 2 (`dvc exp` stuff)
Create dvc.yaml file that contains stages and references `training_config.toml` like so:
```yaml
    params:
      - training_config.toml # track specific params from custom file
          - epochs 
          - ...
```
Run a dummy experiment with mini data
If everything works: 
commit the files related to `dvc exp`-workflow; 
remove the dummy experiment
add an entry in README that explains the dvc exp workflow (see other comments on this issue)

**Comment by ybracke** [comment]
#### Part 2 (`dvc exp` stuff)
Create dvc.yaml file that contains stages and references `training_config.toml` like so:
```yaml
    params:
      - training_config.toml # track specific params from custom file
          - epochs 
          - ...
```
Run a dummy experiment with mini data
If everything works: 
commit the files related to `dvc exp`-workflow; 
remove the dummy experiment
add an entry in README that explains the dvc exp workflow (see other comments on this issue)

**Comment by ybracke** [comment]
#### Part 2

- [ ] Set-up local remote storage with dvc for data/model files
- [ ] Test whether it works to push/pull from local remote storage

**Comment by ybracke** [comment]
#

**Comment by ybracke** [comment]
* There will be still work to do after this issue is closed, e.g. #51
